table 'Economic Data'
	lineageTag: 5b440f69-5a85-4844-92c8-c5a8ccb374c0

	column date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 9c1819b0-27b9-4fc3-a6b2-7d70b3354b0b
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Attribute
		dataType: string
		isHidden
		lineageTag: 310496e7-3d9c-4012-97cc-57928d4e539f
		summarizeBy: none
		sourceColumn: Attribute

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: cbf853eb-2bc5-4b88-8099-5aa53bc90c3f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Economic Data' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Headline CPI", #"Fed Rate", #"10-Year Treasury Yield", #"30-Year Mortgage Rates", #"Unemployment Rate", #"Consumer Sentiment", #"Core CPI", GDP}),
				    #"Filtered Rows" = Table.SelectRows(Source, each Date.IsInPreviousNYears([date], 30) or Date.IsInCurrentYear([date]))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

